defmodule Scriba do
  @moduledoc """
  Public API surface for Scriba projections.

  ## The five-line API

      defmodule MyApp.Projections.Orders do
        use Scriba.Projection,
          name: "orders",
          source: {Scriba.Source.Commanded, application: MyApp.CommandedApp},
          target: {Scriba.Target.Ecto, repo: MyApp.Repo},
          parallelism: 16

        def handle(_event, _meta), do: :skip
      end

      {:ok, _pid} = Scriba.start_projection(MyApp.Projections.Orders)
      Scriba.info(MyApp.Projections.Orders)
      Scriba.pause(MyApp.Projections.Orders)
      Scriba.resume(MyApp.Projections.Orders)
      Scriba.stop(MyApp.Projections.Orders)
      Scriba.list()

  Every public function accepts either:

    * **Module form** — `Scriba.pause(MyApp.Projections.Orders)`. The
      module's `__scriba_config__/0` (generated by
      `use Scriba.Projection`) provides name and version. Refactor-
      friendly: rename the module, the call site renames with it.
    * **String form** — `Scriba.pause("orders", 1)`. Operator-friendly
      when you only know the projection's name. Defaults to version 1
      for the arity-1 calls.

  `Scriba.list/0` enumerates running projections via `Scriba.Registry`.
  """

  require Logger

  alias Scriba.Info
  alias Scriba.Projection.Coordinator

  @stream_position_truncation_limit 1000

  ## Lifecycle — start / list

  @doc """
  Starts a projection from its module's compile-time config.

  Reads the projection's `__scriba_config__/0` map (generated by
  `use Scriba.Projection`) and starts a `Scriba.Projection.Supervisor`
  under `Scriba.Projections.Supervisor`. Returns the per-projection
  supervisor pid.

  Returns immediately (does not wait for the Coordinator to transition
  from `:initializing` to `:running`). Wait for the
  `[:scriba, :projection, :started]` telemetry event or poll
  `Scriba.info/1` if you need a confirmation point.

  Returns `{:error, :already_started}` if a projection with the same
  `(name, version)` is already running.
  """
  @spec start_projection(module()) ::
          {:ok, pid()} | {:error, :already_started | term()}
  def start_projection(module) when is_atom(module) do
    start_projection(module, [])
  end

  @doc """
  Same as `start_projection/1`, but merges `overrides` into the module's
  compile-time config before starting.

  Useful for runtime tuning of `:parallelism`, `:batch_size`, `:retry`,
  etc. per-environment without recompiling the module.

  **Rejects `:name` and `:version` overrides** with `ArgumentError`.
  Identity is compile-time: passing a different name/version at runtime
  would silently create a *different* projection rather than override
  the existing one's config, which is almost certainly a bug. If you
  want a second projection with a different version, declare a second
  module with `version: 2` in its `use`.
  """
  @spec start_projection(module(), keyword()) ::
          {:ok, pid()} | {:error, :already_started | term()}
  def start_projection(module, overrides) when is_atom(module) and is_list(overrides) do
    config = load_config!(module)

    case Enum.find(overrides, fn {k, _} -> k in [:name, :version] end) do
      nil ->
        :ok

      {bad_key, _} ->
        raise ArgumentError, """
        Scriba.start_projection/2 cannot override :#{bad_key} at runtime — it is part
        of the projection's identity, set at compile time via `use Scriba.Projection`.
        Got override: #{inspect(bad_key)}=#{inspect(Keyword.get(overrides, bad_key))}
        """
    end

    opts =
      config
      |> Map.to_list()
      |> Keyword.merge(overrides)

    case DynamicSupervisor.start_child(
           Scriba.Projections.Supervisor,
           {Scriba.Projection.Supervisor, opts}
         ) do
      {:ok, pid} -> {:ok, pid}
      # Both shapes mean the same thing to a caller: this projection is
      # already running. The pid is the existing one, not a new child.
      {:error, {:already_started, _pid}} -> {:error, :already_started}
      {:error, :already_started} -> {:error, :already_started}
      other -> other
    end
  end

  @doc """
  Returns running projections as `[%{name, version, state}]`.

  Enumerates Coordinators registered in `Scriba.Registry`; includes
  projections in any state, including `:stopped` (terminal Coordinators
  that haven't been terminated from the supervision tree). Empty list
  when no projections are running.
  """
  @spec list() :: [%{name: String.t(), version: pos_integer(), state: atom()}]
  def list do
    # Match spec: select Registry entries whose KEY shape is
    # {:coordinator, name, version} and extract the {name, version} pair.
    # See Registry.select/2 docs for the match-spec grammar.
    Scriba.Registry
    |> Registry.select([
      {{{:coordinator, :"$1", :"$2"}, :_, :_}, [], [{{:"$1", :"$2"}}]}
    ])
    |> Enum.map(fn {name, version} ->
      case Coordinator.get_status(name, version) do
        {:ok, status} -> %{name: name, version: version, state: status.state}
        # Coordinator was registered but disappeared between select and
        # get_status — race during shutdown. Skip.
        {:error, :not_found} -> nil
      end
    end)
    |> Enum.reject(&is_nil/1)
  end

  ## Lifecycle — info / pause / resume / stop (module + string forms)

  @doc """
  Returns a snapshot of the projection's runtime state. See `Scriba.Info` for
  the shape.

  Accepts either a projection module or a `(name, version)` pair. The
  arity-1 string form defaults to version 1.

  Returns `{:error, :not_found}` if no Coordinator is registered for the
  given identity.

  When the projection has more than #{@stream_position_truncation_limit}
  distinct streams, `:stream_positions` is `:truncated` rather than a
  giant map; `:safe_position` is always populated regardless.

  `:safe_position` is the minimum across *cached* streams — an introspection
  figure, not a replay point. See `Scriba.Info` for why
  it reads high and what it is not safe to build on.

  The `:status` field is one of `:initializing | :running | :paused |
  :draining | :halted | :stopped`. `:initializing` is the brief window between
  Coordinator start and Broadway producer registration; transitions to
  `:running` automatically.

  `:halted` means a structural commit failure stopped the projection — it is
  making no progress and needs a human. `:halt_reason` names the cause. This
  is the field to poll if you want to detect a stopped projection without
  subscribing to telemetry.
  """
  @spec info(module() | String.t()) :: {:ok, Info.t()} | {:error, :not_found}
  def info(module_or_name)

  def info(module) when is_atom(module) and module not in [nil, true, false] do
    config = load_config!(module)
    info(config.name, config.version)
  end

  def info(name) when is_binary(name), do: info(name, 1)

  @doc "See `info/1`. Takes explicit `name` (string) and `version` (integer)."
  @spec info(String.t(), pos_integer()) :: {:ok, Info.t()} | {:error, :not_found}
  def info(name, version) when is_binary(name) and is_integer(version) do
    case Coordinator.get_status(name, version) do
      {:ok, status} -> {:ok, build_info(name, version, status)}
      {:error, :not_found} -> {:error, :not_found}
    end
  end

  @doc """
  Lists a projection's dead letters, newest first.

      Scriba.dead_letters(MyApp.Projections.Orders, limit: 10)
      Scriba.dead_letters(MyApp.Projections.Orders, stream_id: "order-42", order: :asc)

  Takes a projection module, or a name and version with an explicit
  `repo:`. The module form reads the repo from the projection's own target
  config, so it works whether or not the projection is running — which is
  the point: a halted or stopped projection is exactly when someone looks.

  See `Scriba.DeadLetter.list/3` for the options and the shape of a row.
  """
  @spec dead_letters(module() | String.t(), keyword()) :: [map()]
  def dead_letters(module_or_name, opts \\ [])

  def dead_letters(module, opts) when is_atom(module) and module not in [nil, true, false] do
    {projection, repo} = resolve_projection!(module, opts)
    Scriba.DeadLetter.list(repo, projection, opts)
  end

  def dead_letters(name, opts) when is_binary(name) do
    {projection, repo} = resolve_projection!(name, opts)
    Scriba.DeadLetter.list(repo, projection, opts)
  end

  @doc """
  How many dead letters, of what kind, over what span.

      %{total: 143,
        by_error_kind: %{"commit:23505 (unique_violation)" => 140},
        oldest: ~U[...], newest: ~U[...]}

  Accepts the same filters as `dead_letters/2`. The distribution is the
  diagnosis: one kind on one stream is a poison event, one kind across every
  stream is a schema problem that dead-lettering is papering over.
  """
  @spec dead_letter_stats(module() | String.t(), keyword()) :: map()
  def dead_letter_stats(module_or_name, opts \\ [])

  def dead_letter_stats(module, opts) when is_atom(module) and module not in [nil, true, false] do
    {projection, repo} = resolve_projection!(module, opts)
    Scriba.DeadLetter.stats(repo, projection, opts)
  end

  def dead_letter_stats(name, opts) when is_binary(name) do
    {projection, repo} = resolve_projection!(name, opts)
    Scriba.DeadLetter.stats(repo, projection, opts)
  end

  @doc """
  Pauses a running projection — the source stops yielding new events.
  In-flight events already in Pipeline processors or batchers continue
  through their commit lifecycle.

  Accepts either a projection module or a name string. Arity-1 string
  form defaults to version 1; see `pause/2` for explicit version.

  ## Return values

    * `:ok` — pause signal sent to the source. The source's `handle_info/2`
      will run on its own schedule; by the time this function returns the
      signal is in the source's mailbox but the source may not yet have
      flipped its internal flag. Operators should NOT assume "no commits
      possible" the instant `pause/1` returns.

    * `{:error, {:invalid_state, state}}` — projection is not in a state
      where pause makes sense. The inner atom is the projection's current
      state:

        - `:initializing` — engine starting up; retry once `info/1`
          reports `:running`.
        - `:paused` — already paused. **No idempotency** — callers wanting
          "make sure this is paused" semantics check `info/1` first or
          pattern-match this error case as success.
        - `:stopped` — terminal state.
        - `:draining` — stop in progress.
        - `:halted` — terminal. A structural commit failure stopped the
          projection; `stop/1` is the way out once the cause is fixed.
  """
  @spec pause(module() | String.t()) :: :ok | {:error, {:invalid_state, atom()}}
  def pause(module_or_name)

  def pause(module) when is_atom(module) and module not in [nil, true, false] do
    config = load_config!(module)
    Coordinator.pause(config.name, config.version)
  end

  def pause(name) when is_binary(name), do: pause(name, 1)

  @doc "See `pause/1`. Takes explicit `name` (string) and `version` (integer)."
  @spec pause(String.t(), pos_integer()) ::
          :ok | {:error, {:invalid_state, atom()}}
  def pause(name, version) when is_binary(name) and is_integer(version),
    do: Coordinator.pause(name, version)

  @doc """
  Resumes a paused projection.

  Accepts a module or name string; same dispatch semantics as `pause/1`.

  ## Return values

    * `:ok` — resume signal sent. Same asynchrony caveat as `pause/1`:
      first commit follows whenever the source's `handle_info/2` runs and
      Broadway's processor stage drains accumulated demand.

    * `{:error, {:invalid_state, state}}` — projection is not paused.
      `:running` is **not** idempotent here either.
  """
  @spec resume(module() | String.t()) :: :ok | {:error, {:invalid_state, atom()}}
  def resume(module_or_name)

  def resume(module) when is_atom(module) and module not in [nil, true, false] do
    config = load_config!(module)
    Coordinator.resume(config.name, config.version)
  end

  def resume(name) when is_binary(name), do: resume(name, 1)

  @doc "See `resume/1`."
  @spec resume(String.t(), pos_integer()) ::
          :ok | {:error, {:invalid_state, atom()}}
  def resume(name, version) when is_binary(name) and is_integer(version),
    do: Coordinator.resume(name, version)

  @doc """
  Stops a running or paused projection. Waits for in-flight Broadway
  shutdown to complete before returning.

  Returns `:ok` on success, `{:error, {:invalid_state, state}}` if the
  projection is `:initializing`, `:stopped`, or `:draining`. A projection
  that is still starting cannot be stopped — wait for `info/1` to report
  `:running`.

  The projection is **not removed**: its Coordinator stays registered in a
  terminal `:stopped` state, so `info/1` keeps answering and `reset/2` can
  still clear its cursors. Starting the same `(name, version)` again fails
  with `{:error, :already_started}` until the supervision child is removed:

      DynamicSupervisor.terminate_child(Scriba.Projections.Supervisor, pid)

  Keeping the row is deliberate — a stopped projection that vanished from
  `list/0` would be indistinguishable from one that never started.
  """
  @spec stop(module() | String.t()) :: :ok | {:error, {:invalid_state, atom()}}
  def stop(module_or_name)

  def stop(module) when is_atom(module) and module not in [nil, true, false] do
    config = load_config!(module)
    Coordinator.stop(config.name, config.version)
  end

  def stop(name) when is_binary(name), do: stop(name, 1)

  @doc "See `stop/1`."
  @spec stop(String.t(), pos_integer()) ::
          :ok | {:error, {:invalid_state, atom()}}
  def stop(name, version) when is_binary(name) and is_integer(version),
    do: Coordinator.stop(name, version)

  @doc """
  Clears a projection version's progress so it can start over.

  Deletes its rows from `scriba_positions` and `scriba_watermarks` and drops
  its entries from the position cache. After this the version has no memory
  of what it applied, so starting it with `start_from: :origin` rebuilds from
  the beginning.

  **It does not touch the read model.** Scriba does not know which tables a
  handler writes — that is the handler's business — so truncating them is
  yours to do, in the same operation, or the rebuild will apply history on
  top of existing rows.

  Dead letters are kept by default: they record what failed on the previous
  attempt and are usually the reason for the rebuild. `dead_letters: true`
  deletes them too.

  Accepts a projection that is stopped or was never started, and refuses
  anything else: clearing cursors under a live pipeline lets it commit
  against a cache that no longer matches the table. `stop/1` leaves the
  Coordinator registered in `:stopped`, and that counts as stopped.

      :ok = Scriba.stop(MyApp.Projections.OrdersV2)

      {:ok, %{positions: 1_284, watermark: 1, dead_letters: 0}} =
        Scriba.reset(MyApp.Projections.OrdersV2)

  ## Options

    * `:dead_letters` — `true` deletes them too (default `false`).
    * `:repo` — required for the name form, which has no config to read it
      from; optional for the module form, which takes it from the
      projection's target.
    * `:version` — for the name form only (default `1`).

  ## Returns

    * `{:ok, %{positions: n, watermark: n, dead_letters: n}}` — rows removed
      per table. `dead_letters` is `0` unless you asked for them.
    * `{:error, {:running, state}}` — the projection is live; stop it first.
    * `{:error, :no_repo}` — no repo was given and none could be resolved.
  """
  @spec reset(module() | String.t(), keyword()) ::
          {:ok, map()} | {:error, {:running, atom()}} | {:error, :no_repo}
  def reset(module_or_name, opts \\ [])

  def reset(module, opts) when is_atom(module) and module not in [nil, true, false] do
    config = load_config!(module)
    repo = Keyword.get(opts, :repo) || Scriba.Position.resolve_repo([], config.target)

    do_reset(config.name, config.version, repo, opts)
  end

  def reset(name, opts) when is_binary(name) do
    do_reset(name, Keyword.get(opts, :version, 1), Keyword.get(opts, :repo), opts)
  end

  defp do_reset(_name, _version, nil, _opts), do: {:error, :no_repo}

  defp do_reset(name, version, repo, opts) do
    projection = %{name: name, version: version}

    # `stop/1` leaves the Coordinator alive in a terminal `:stopped` state,
    # still registered, so "not found" is not the only way to be stopped —
    # and refusing to reset a stopped projection would refuse the normal
    # case. Anything else still has a live pipeline that could commit against
    # the cache this is about to clear.
    case Coordinator.get_status(name, version) do
      {:ok, %{state: :stopped}} -> {:ok, Scriba.Reset.run(repo, projection, opts)}
      {:ok, status} -> {:error, {:running, Map.get(status, :state)}}
      {:error, :not_found} -> {:ok, Scriba.Reset.run(repo, projection, opts)}
    end
  end

  # Resolves `{projection, repo}` for the functions that read or clear a
  # projection's stored state: dead_letters/2, dead_letter_stats/2, reset/2.
  #
  # A module knows its own repo; a name does not, so the caller supplies one.
  # Reading config rather than asking the Coordinator is deliberate: these
  # rows outlive the process that produced them, and the projection is often
  # stopped — or gone — by the time anyone reads them.
  defp resolve_projection!(module, opts) when is_atom(module) do
    config = load_config!(module)

    projection = %{
      name: Keyword.get(opts, :name, config.name),
      version: Keyword.get(opts, :version, config.version)
    }

    repo = Keyword.get(opts, :repo) || Scriba.Position.resolve_repo([], config.target)

    unless repo do
      raise ArgumentError, """
      Cannot read dead letters for #{inspect(module)}: no repo.

      #{inspect(module)}'s target does not carry one, so pass it:

          Scriba.dead_letters(#{inspect(module)}, repo: MyApp.Repo)
      """
    end

    {projection, repo}
  end

  defp resolve_projection!(name, opts) when is_binary(name) do
    repo = Keyword.get(opts, :repo)

    unless repo do
      raise ArgumentError, """
      Cannot read dead letters for #{inspect(name)}: no repo.

      The name form does not know which repo holds them, so pass one:

          Scriba.dead_letters(#{inspect(name)}, repo: MyApp.Repo)

      Or pass the projection module, which knows its own.
      """
    end

    {%{name: name, version: Keyword.get(opts, :version, 1)}, repo}
  end

  defp load_config!(module) do
    unless Code.ensure_loaded?(module) do
      raise ArgumentError, """
      Module #{inspect(module)} is not loaded. Cannot read Scriba projection config.
      Make sure the module is compiled and the application is started before calling.
      """
    end

    unless function_exported?(module, :__scriba_config__, 0) do
      raise ArgumentError, """
      Module #{inspect(module)} does not appear to be a Scriba projection.
      Expected #{inspect(module)} to be defined with `use Scriba.Projection, ...`.
      """
    end

    module.__scriba_config__()
  end

  defp build_info(name, version, status) do
    streams = Scriba.Position.stream_positions(name, version)
    safe = Scriba.Position.safe_position(name, version)

    stream_positions =
      if map_size(streams) > @stream_position_truncation_limit do
        :truncated
      else
        streams
      end

    watermark = watermark_for(name, version, Map.get(status, :target))

    %Info{
      name: name,
      version: version,
      status: Map.get(status, :state),
      source: Map.get(status, :source),
      target: Map.get(status, :target),
      safe_position: safe,
      stream_positions: stream_positions,
      halt_reason: Map.get(status, :halt_reason),
      watermark: watermark && watermark.position,
      lag_ms: lag_ms(watermark)
    }
  end

  # Reading the watermark is a database round-trip, so it is best-effort: a
  # repo that is momentarily unreachable should not stop info/2 reporting the
  # status, which is the field an operator is most likely to be asking for.
  defp watermark_for(name, version, target_spec) do
    case Scriba.Position.resolve_repo([], target_spec) do
      nil -> nil
      repo -> Scriba.Watermark.get(repo, %{name: name, version: version})
    end
  rescue
    # info/2's job is to answer about the projection, and :status is the field
    # an operator is most likely asking for — a watermark read that fails must
    # not take the whole answer with it. It is logged rather than swallowed,
    # because a nil watermark otherwise reads as "nothing committed yet" when
    # the truth may be "this repo is unreachable".
    exception ->
      Logger.debug(
        "Scriba could not read the watermark for #{name} v#{version}: " <>
          Exception.message(exception)
      )

      nil
  end

  defp lag_ms(%{occurred_at: %DateTime{} = occurred_at}) do
    DateTime.utc_now() |> DateTime.diff(occurred_at, :millisecond) |> max(0)
  end

  defp lag_ms(_), do: nil
end
